In [2]:
%pip install pandas

Requirement already satisfied: pandas in /Users/niranjanhebli/Desktop/Week3/week3/.venv/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: pytz>=2020.1 in /Users/niranjanhebli/Desktop/Week3/week3/.venv/lib/python3.9/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /Users/niranjanhebli/Desktop/Week3/week3/.venv/lib/python3.9/site-packages (from pandas) (2025.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/niranjanhebli/Desktop/Week3/week3/.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in /Users/niranjanhebli/Desktop/Week3/week3/.venv/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: six>=1.5 in /Users/niranjanhebli/Desktop/Week3/week3/.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/niranjanhebli/Desktop/Week3/week3/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
employees = pd.read_csv("data/employees.csv")
offices = pd.read_csv("data/offices.csv")
customers = pd.read_csv("data/customers.csv")
monthly_salaries = pd.read_csv("data/monthly_salaries.csv")

In [5]:
print(employees.head())

   employeeNumber   lastName firstName  officeCode  reportsTo  \
0            1002     Murphy     Diane           1        NaN
1            1056  Patterson      Mary           1     1002.0
2            1076   Firrelli      Jeff           1     1002.0
3            1088  Patterson   William           6     1056.0
4            1102     Bondur    Gerard           4     1056.0

               jobTitle  salary
0             President  150000
1              VP Sales  140000
2          VP Marketing  130000
3  Sales Manager (APAC)  120000
4   Sale Manager (EMEA)  115000

In [6]:
print(offices.head())

   officeCode           city            phone country
0           1  San Francisco  +1 650 219 4782     USA
1           2         Boston  +1 215 837 0825     USA
2           3            NYC  +1 212 555 3000     USA
3           4          Paris  +33 14 723 4404  France
4           5          Tokyo  +81 33 224 5000   Japan

In [7]:
print(customers.head())

   customerNumber                customerName  salesRepEmployeeNumber  \
0             103           Atelier graphique                  1370.0
1             112          Signal Gift Stores                  1166.0
2             114  Australian Collectors, Co.                  1611.0
3             119           La Rochelle Gifts                  1370.0
4             121          Baane Mini Imports                  1504.0

     country
0     France
1        USA
2  Australia
3     France
4     Norway

In [8]:
print(monthly_salaries.head())

   employeeNumber    month  salary
0            1002  2024-01  150000
1            1002  2024-02  152000
2            1002  2024-03  149500
3            1002  2024-04  151200
4            1002  2024-05  153800

### 1. Get all employees working in USA

In [9]:
emp_office = employees.merge(offices, on='officeCode')
employees_usa = emp_office[emp_office['country'] == 'USA']
employees_usa

,employeeNumber,lastName,firstName,officeCode,reportsTo,jobTitle,salary,city,phone,country
0,1002,Murphy,Diane,1,NaN,President,150000,San Francisco,+1 650 219 4782,USA
1,1056,Patterson,Mary,1,1002.0,VP Sales,140000,San Francisco,+1 650 219 4782,USA
2,1076,Firrelli,Jeff,1,1002.0,VP Marketing,130000,San Francisco,+1 650 219 4782,USA
5,1143,Bow,Anthony,1,1056.0,Sales Manager (NA),118000,San Francisco,+1 650 219 4782,USA
6,1165,Jennings,Leslie,1,1143.0,Sales Rep,90000,San Francisco,+1 650 219 4782,USA
7,1166,Thompson,Leslie,1,1143.0,Sales Rep,85000,San Francisco,+1 650 219 4782,USA
8,1188,Firrelli,Julie,2,1143.0,Sales Rep,88000,Boston,+1 215 837 0825,USA
9,1216,Patterson,Steve,2,1143.0,Sales Rep,87000,Boston,+1 215 837 0825,USA
10,1286,Tseng,Foon Yue,3,1143.0,Sales Rep,92000,NYC,+1 212 555 3000,USA
11,1323,Vanauf,George,3,1143.0,Sales Rep,91000,NYC,+1 212 555 3000,USA

### 2. Get all employees with salary greater than 100000

In [10]:
salary_gt_100000 = employees[employees['salary'] > 100000]
salary_gt_100000

,employeeNumber,lastName,firstName,officeCode,reportsTo,jobTitle,salary
0,1002,Murphy,Diane,1,NaN,President,150000
1,1056,Patterson,Mary,1,1002.0,VP Sales,140000
2,1076,Firrelli,Jeff,1,1002.0,VP Marketing,130000
3,1088,Patterson,William,6,1056.0,Sales Manager (APAC),120000
4,1102,Bondur,Gerard,4,1056.0,Sale Manager (EMEA),115000
5,1143,Bow,Anthony,1,1056.0,Sales Manager (NA),118000

### 3. Get all employees who have sales rep role

In [11]:
sales_reps = employees[employees['jobTitle'] == 'Sales Rep']
sales_reps

,employeeNumber,lastName,firstName,officeCode,reportsTo,jobTitle,salary
6,1165,Jennings,Leslie,1,1143.0,Sales Rep,90000
7,1166,Thompson,Leslie,1,1143.0,Sales Rep,85000
8,1188,Firrelli,Julie,2,1143.0,Sales Rep,88000
9,1216,Patterson,Steve,2,1143.0,Sales Rep,87000
10,1286,Tseng,Foon Yue,3,1143.0,Sales Rep,92000
11,1323,Vanauf,George,3,1143.0,Sales Rep,91000
12,1337,Bondur,Loui,4,1102.0,Sales Rep,86000
13,1370,Hernandez,Gerard,4,1102.0,Sales Rep,89000
14,1401,Castillo,Pamela,4,1102.0,Sales Rep,88000
15,1501,Bott,Larry,7,1102.0,Sales Rep,90000
16,1504,Jones,Barry,7,1102.0,Sales Rep,91000
17,1611,Fixter,Andy,6,1088.0,Sales Rep,87000
18,1612,Marsh,Peter,6,1088.0,Sales Rep,88000
19,1619,King,Tom,6,1088.0,Sales Rep,89000
20,1621,Nishi,Mami,5,1056.0,Sales Rep,95000
21,1625,Kato,Yoshimi,5,1621.0,Sales Rep,92000
22,1702,Gerard,Martin,4,1102.0,Sales Rep,85000

### 4. Get all employees who reports to employee with employee number 1056

In [12]:
reports_to_1056 = employees[employees['reportsTo'] == 1056]
reports_to_1056

,employeeNumber,lastName,firstName,officeCode,reportsTo,jobTitle,salary
3,1088,Patterson,William,6,1056.0,Sales Manager (APAC),120000
4,1102,Bondur,Gerard,4,1056.0,Sale Manager (EMEA),115000
5,1143,Bow,Anthony,1,1056.0,Sales Manager (NA),118000
20,1621,Nishi,Mami,5,1056.0,Sales Rep,95000

### 5. Get all employee records who live in city Paris

In [13]:
lives_in_paris = emp_office[emp_office['city'] == 'Paris']
lives_in_paris

,employeeNumber,lastName,firstName,officeCode,reportsTo,jobTitle,salary,city,phone,country
4,1102,Bondur,Gerard,4,1056.0,Sale Manager (EMEA),115000,Paris,+33 14 723 4404,France
12,1337,Bondur,Loui,4,1102.0,Sales Rep,86000,Paris,+33 14 723 4404,France
13,1370,Hernandez,Gerard,4,1102.0,Sales Rep,89000,Paris,+33 14 723 4404,France
14,1401,Castillo,Pamela,4,1102.0,Sales Rep,88000,Paris,+33 14 723 4404,France
22,1702,Gerard,Martin,4,1102.0,Sales Rep,85000,Paris,+33 14 723 4404,France

 ### 6. Get all employee records with office details (city and country)

In [14]:
emp_office[['employeeNumber','firstName','lastName','city','country']]

    employeeNumber firstName   lastName           city    country
0             1002     Diane     Murphy  San Francisco        USA
1             1056      Mary  Patterson  San Francisco        USA
2             1076      Jeff   Firrelli  San Francisco        USA
3             1088   William  Patterson         Sydney  Australia
4             1102    Gerard     Bondur          Paris     France
5             1143   Anthony        Bow  San Francisco        USA
6             1165    Leslie   Jennings  San Francisco        USA
7             1166    Leslie   Thompson  San Francisco        USA
8             1188     Julie   Firrelli         Boston        USA
9             1216     Steve  Patterson         Boston        USA
10            1286  Foon Yue      Tseng            NYC        USA
11            1323    George     Vanauf            NYC        USA
12            1337      Loui     Bondur          Paris     France
13            1370    Gerard  Hernandez          Paris     France
14            1401    Pamela   Castillo          Paris     France
15            1501     Larry       Bott         London         UK
16            1504     Barry      Jones         London         UK
17            1611      Andy     Fixter         Sydney  Australia
18            1612     Peter      Marsh         Sydney  Australia
19            1619       Tom       King         Sydney  Australia
20            1621      Mami      Nishi          Tokyo      Japan
21            1625   Yoshimi       Kato          Tokyo      Japan
22            1702    Martin     Gerard          Paris     France

###  7. Get all sales reps with their customer count (including those with zero customers)

In [15]:
sales_rep_customers = employees.merge(
    customers,
    left_on='employeeNumber',
    right_on='salesRepEmployeeNumber',
    how='left'
)

sales_rep_customer_count = (
    sales_rep_customers[sales_rep_customers['jobTitle'] == 'Sales Rep']
    .groupby(['employeeNumber', 'firstName', 'lastName'])
    .agg(customers=('customerNumber', 'count'))
    .reset_index()
)

sales_rep_customer_count

    employeeNumber firstName   lastName  customers
0             1165    Leslie   Jennings          2
1             1166    Leslie   Thompson          1
2             1188     Julie   Firrelli          0
3             1216     Steve  Patterson          0
4             1286  Foon Yue      Tseng          0
5             1323    George     Vanauf          1
6             1337      Loui     Bondur          0
7             1370    Gerard  Hernandez          2
8             1401    Pamela   Castillo          0
9             1501     Larry       Bott          0
10            1504     Barry      Jones          2
11            1611      Andy     Fixter          1
12            1612     Peter      Marsh          0
13            1619       Tom       King          0
14            1621      Mami      Nishi          0
15            1625   Yoshimi       Kato          0
16            1702    Martin     Gerard          0

### 8. Get all managers with their direct reports count

In [16]:
manager_reports = employees.merge(
    employees,
    left_on='employeeNumber',
    right_on='reportsTo',
    suffixes=('_manager', '_employee')
)

manager_reports = manager_reports[
    manager_reports['jobTitle_manager'].str.contains('Manager', na=False)
]

manager_reports[['firstName_manager', 'lastName_manager', 'firstName_employee', 'lastName_employee']]

   firstName_manager lastName_manager firstName_employee lastName_employee
6            William        Patterson               Andy            Fixter
7            William        Patterson              Peter             Marsh
8            William        Patterson                Tom              King
9             Gerard           Bondur               Loui            Bondur
10            Gerard           Bondur             Gerard         Hernandez
11            Gerard           Bondur             Pamela          Castillo
12            Gerard           Bondur              Larry              Bott
13            Gerard           Bondur              Barry             Jones
14            Gerard           Bondur             Martin            Gerard
15           Anthony              Bow             Leslie          Jennings
16           Anthony              Bow             Leslie          Thompson
17           Anthony              Bow              Julie          Firrelli
18           Anthony              Bow              Steve         Patterson
19           Anthony              Bow           Foon Yue             Tseng
20           Anthony              Bow             George            Vanauf

### 9. Get all sales reps who do not have any customers assigned

In [17]:
sales_reps_no_customers = sales_rep_customers[
    (sales_rep_customers['jobTitle'] == 'Sales Rep') &
    (sales_rep_customers['customerNumber'].isna())
]

sales_reps_no_customers

,employeeNumber,lastName,firstName,officeCode,reportsTo,jobTitle,salary,customerNumber,customerName,salesRepEmployeeNumber,country
9,1188,Firrelli,Julie,2,1143.0,Sales Rep,88000,NaN,NaN,NaN,NaN
10,1216,Patterson,Steve,2,1143.0,Sales Rep,87000,NaN,NaN,NaN,NaN
11,1286,Tseng,Foon Yue,3,1143.0,Sales Rep,92000,NaN,NaN,NaN,NaN
13,1337,Bondur,Loui,4,1102.0,Sales Rep,86000,NaN,NaN,NaN,NaN
16,1401,Castillo,Pamela,4,1102.0,Sales Rep,88000,NaN,NaN,NaN,NaN
17,1501,Bott,Larry,7,1102.0,Sales Rep,90000,NaN,NaN,NaN,NaN
21,1612,Marsh,Peter,6,1088.0,Sales Rep,88000,NaN,NaN,NaN,NaN
22,1619,King,Tom,6,1088.0,Sales Rep,89000,NaN,NaN,NaN,NaN
23,1621,Nishi,Mami,5,1056.0,Sales Rep,95000,NaN,NaN,NaN,NaN
24,1625,Kato,Yoshimi,5,1621.0,Sales Rep,92000,NaN,NaN,NaN,NaN
25,1702,Gerard,Martin,4,1102.0,Sales Rep,85000,NaN,NaN,NaN,NaN

### 10. Get the number of sales reps per country

In [18]:
sales_reps_per_country = (
    emp_office[emp_office['jobTitle'] == 'Sales Rep']
    .groupby('country')
    .size()
    .reset_index(name='reps')
)

sales_reps_per_country

     country  reps
0  Australia     3
1     France     4
2      Japan     2
3         UK     2
4        USA     6

### 11. Get the average salary per office

In [19]:
avg_salary_per_office = (
    employees.groupby('officeCode')['salary']
    .mean()
    .reset_index(name='avg_salary')
)

avg_salary_per_office

   officeCode     avg_salary
0           1  118833.333333
1           2   87500.000000
2           3   91500.000000
3           4   92600.000000
4           5   93500.000000
5           6   96000.000000
6           7   90500.000000

###  12. Get the number of employees per country

In [20]:
employees_per_country = (
    emp_office.groupby('country')
    .size()
    .reset_index(name='no_of_employees')
)

employees_per_country

     country  no_of_employees
0  Australia                4
1     France                5
2      Japan                2
3         UK                2
4        USA               10

### 13. Get the job title with the highest number of employees

In [21]:
top_job_title = employees['jobTitle'].value_counts().reset_index().head(1)
top_job_title

    jobTitle  count
0  Sales Rep     17

### 14. Get the maximum salary for each manager (reportsTo)

In [22]:
max_salary_per_manager = (
    employees.dropna(subset=['reportsTo'])
    .groupby('reportsTo')['salary']
    .max()
    .reset_index(name='max_salary')
)

max_salary_per_manager

   reportsTo  max_salary
0     1002.0      140000
1     1056.0      120000
2     1088.0       89000
3     1102.0       91000
4     1143.0       92000
5     1621.0       92000

### 15. Get the number of employees reporting to VPs

In [23]:
vp_ids = employees[
    employees['jobTitle'].str.contains('VP', na=False)
]['employeeNumber']

reports_to_vps = (
    employees[employees['reportsTo'].isin(vp_ids)]
    .groupby('jobTitle')
    .size()
    .reset_index(name='count')
)

reports_to_vps

               jobTitle  count
0   Sale Manager (EMEA)      1
1  Sales Manager (APAC)      1
2    Sales Manager (NA)      1
3             Sales Rep      1

### 16. Get the ranking of sales reps based on their customer count, partitioned by country and globally

In [24]:
rank_df = (
    sales_rep_customers[sales_rep_customers['jobTitle'] == 'Sales Rep']
    .groupby(['employeeNumber', 'firstName', 'lastName', 'officeCode'])
    .agg(customer_count=('customerNumber', 'count'))
    .reset_index()
)

rank_df = rank_df.merge(offices[['officeCode', 'country']], on='officeCode')

rank_df['country_rank'] = rank_df.groupby('country')['customer_count'].rank(method='dense', ascending=False)
rank_df['global_rank'] = rank_df['customer_count'].rank(method='dense', ascending=False)

rank_df

,employeeNumber,firstName,lastName,officeCode,customer_count,country,country_rank,global_rank
0,1165,Leslie,Jennings,1,2,USA,1.0,1.0
1,1166,Leslie,Thompson,1,1,USA,2.0,2.0
2,1188,Julie,Firrelli,2,0,USA,3.0,3.0
3,1216,Steve,Patterson,2,0,USA,3.0,3.0
4,1286,Foon Yue,Tseng,3,0,USA,3.0,3.0
5,1323,George,Vanauf,3,1,USA,2.0,2.0
6,1337,Loui,Bondur,4,0,France,2.0,3.0
7,1370,Gerard,Hernandez,4,2,France,1.0,1.0
8,1401,Pamela,Castillo,4,0,France,2.0,3.0
9,1501,Larry,Bott,7,0,UK,2.0,3.0
10,1504,Barry,Jones,7,2,UK,1.0,1.0
11,1611,Andy,Fixter,6,1,Australia,1.0,2.0
12,1612,Peter,Marsh,6,0,Australia,2.0,3.0
13,1619,Tom,King,6,0,Australia,2.0,3.0
14,1621,Mami,Nishi,5,0,Japan,1.0,3.0
15,1625,Yoshimi,Kato,5,0,Japan,1.0,3.0
16,1702,Martin,Gerard,4,0,France,2.0,3.0

### 17. Get the top 3 highest paid employees in each office

In [25]:
top_paid = employees.copy()

top_paid['rank'] = top_paid.groupby('officeCode')['salary'].rank(method='dense', ascending=False)

top3_paid = top_paid[top_paid['rank'] <= 3]

top3_paid

,employeeNumber,lastName,firstName,officeCode,reportsTo,jobTitle,salary,rank
0,1002,Murphy,Diane,1,NaN,President,150000,1.0
1,1056,Patterson,Mary,1,1002.0,VP Sales,140000,2.0
2,1076,Firrelli,Jeff,1,1002.0,VP Marketing,130000,3.0
3,1088,Patterson,William,6,1056.0,Sales Manager (APAC),120000,1.0
4,1102,Bondur,Gerard,4,1056.0,Sale Manager (EMEA),115000,1.0
8,1188,Firrelli,Julie,2,1143.0,Sales Rep,88000,1.0
9,1216,Patterson,Steve,2,1143.0,Sales Rep,87000,2.0
10,1286,Tseng,Foon Yue,3,1143.0,Sales Rep,92000,1.0
11,1323,Vanauf,George,3,1143.0,Sales Rep,91000,2.0
13,1370,Hernandez,Gerard,4,1102.0,Sales Rep,89000,2.0
14,1401,Castillo,Pamela,4,1102.0,Sales Rep,88000,3.0
15,1501,Bott,Larry,7,1102.0,Sales Rep,90000,2.0
16,1504,Jones,Barry,7,1102.0,Sales Rep,91000,1.0
18,1612,Marsh,Peter,6,1088.0,Sales Rep,88000,3.0
19,1619,King,Tom,6,1088.0,Sales Rep,89000,2.0
20,1621,Nishi,Mami,5,1056.0,Sales Rep,95000,1.0
21,1625,Kato,Yoshimi,5,1621.0,Sales Rep,92000,2.0


### 18. Get the month-over-month salary growth percentage for each employee

In [26]:
monthly_salaries = monthly_salaries.sort_values(['employeeNumber', 'month'])

monthly_salaries['prev_month'] = monthly_salaries.groupby('employeeNumber')['salary'].shift(1)

monthly_salaries['growth_pct'] = (
    (monthly_salaries['salary'] - monthly_salaries['prev_month']) /
    monthly_salaries['prev_month'] * 100
)
monthly_salaries

    employeeNumber    month  salary  prev_month  growth_pct
0             1002  2024-01  150000         NaN         NaN
1             1002  2024-02  152000    150000.0    1.333333
2             1002  2024-03  149500    152000.0   -1.644737
3             1002  2024-04  151200    149500.0    1.137124
4             1002  2024-05  153800    151200.0    1.719577
5             1002  2024-06  152500    153800.0   -0.845254
6             1002  2024-07  154200    152500.0    1.114754
7             1002  2024-08  155000    154200.0    0.518807
8             1002  2024-09  153200    155000.0   -1.161290
9             1002  2024-10  156000    153200.0    1.827676
10            1002  2024-11  157500    156000.0    0.961538
11            1002  2024-12  158000    157500.0    0.317460
12            1056  2024-01  140000         NaN         NaN
13            1056  2024-02  141500    140000.0    1.071429
14            1056  2024-03  139800    141500.0   -1.201413
15            1056  2024-04  142200    139800.0    1.716738
16            1056  2024-05  143000    142200.0    0.562588
17            1056  2024-06  141900    143000.0   -0.769231
18            1056  2024-07  144500    141900.0    1.832276
19            1056  2024-08  145200    144500.0    0.484429
20            1056  2024-09  143800    145200.0   -0.964187
21            1056  2024-10  146000    143800.0    1.529903
22            1056  2024-11  147300    146000.0    0.890411
23            1056  2024-12  148000    147300.0    0.475221
24            1165  2024-01   90000         NaN         NaN
25            1165  2024-02   91000     90000.0    1.111111
26            1165  2024-03   89500     91000.0   -1.648352
27            1165  2024-04   92000     89500.0    2.793296
28            1165  2024-05   92500     92000.0    0.543478
29            1165  2024-06   91500     92500.0   -1.081081
30            1165  2024-07   93000     91500.0    1.639344
31            1165  2024-08   93500     93000.0    0.537634
32            1165  2024-09   92200     93500.0   -1.390374
33            1165  2024-10   94000     92200.0    1.952278
34            1165  2024-11   94500     94000.0    0.531915
35            1165  2024-12   95200     94500.0    0.740741

### 19. Get all employees whose salary is above the average salary of their office

In [27]:
overall_avg = employees['salary'].mean()

high_earners = employees[employees['salary'] > overall_avg]

office_avg = employees.groupby('officeCode')['salary'].mean().reset_index(name='avg')

high_earners_above_avg = high_earners.merge(office_avg, on='officeCode')

high_earners_above_avg = high_earners_above_avg[
    high_earners_above_avg['salary'] > high_earners_above_avg['avg']
]

high_earners_above_avg

,employeeNumber,lastName,firstName,officeCode,reportsTo,jobTitle,salary,avg
0,1002,Murphy,Diane,1,NaN,President,150000,118833.333333
1,1056,Patterson,Mary,1,1002.0,VP Sales,140000,118833.333333
2,1076,Firrelli,Jeff,1,1002.0,VP Marketing,130000,118833.333333
3,1088,Patterson,William,6,1056.0,Sales Manager (APAC),120000,96000.000000
4,1102,Bondur,Gerard,4,1056.0,Sale Manager (EMEA),115000,92600.000000

### 20. Get all employees whose salary is above the average salary of their office (without using CTEs)

In [28]:
office_mean = employees.groupby('officeCode')['salary'].transform('mean')

salary_above_office_avg = employees[employees['salary'] > office_mean]

print(salary_above_office_avg)

    employeeNumber   lastName firstName  officeCode  reportsTo  \
0             1002     Murphy     Diane           1        NaN
1             1056  Patterson      Mary           1     1002.0
2             1076   Firrelli      Jeff           1     1002.0
3             1088  Patterson   William           6     1056.0
4             1102     Bondur    Gerard           4     1056.0
8             1188   Firrelli     Julie           2     1143.0
10            1286      Tseng  Foon Yue           3     1143.0
16            1504      Jones     Barry           7     1102.0
20            1621      Nishi      Mami           5     1056.0

                jobTitle  salary
0              President  150000
1               VP Sales  140000
2           VP Marketing  130000
3   Sales Manager (APAC)  120000
4    Sale Manager (EMEA)  115000
8              Sales Rep   88000
10             Sales Rep   92000
16             Sales Rep   91000
20             Sales Rep   95000

### Report one insight about how PostgreSQL executes each.

#### Filter Query (WHERE salary > 100000)
- PostgreSQL usually performs a Sequential Scan, meaning it checks each row because the table is small or no index exists on salary.

#### Join Query (employees JOIN offices)
- PostgreSQL often uses a Hash Join, where it creates a hash table for the smaller table (offices) to match rows efficiently.

#### Aggregation Query (GROUP BY officeCode)
- PostgreSQL typically uses HashAggregate, which groups rows in memory before calculating aggregate values like averages.